# .github/workflows/vulnify-scan.yml (no repo da CLI)
name: Vulnify Scan

on:
  workflow_call:
    inputs:
      fail_on:
        required: false
        default: any
        type: string
    secrets:
      VULNIFY_API_KEY:
        required: false

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  scan:
    runs-on: ubuntu-latest
    env:
      VULNIFY_FAIL_ON: ${{ inputs.fail_on }}
      # VULNIFY_API_KEY estará disponível se o chamador passar (secrets: inherit)
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install --no-fund --no-audit vulnify

      - id: runscan
        run: |
          npx vulnify test --output json || true
          if [ ! -f vulnify-report.json ]; then
            echo '{"summary":{"critical":0,"high":0,"medium":0,"low":0}}' > vulnify-report.json
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: vulnify-report
          path: vulnify-report.json

      - if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const p = 'vulnify-report.json';
            let s = {critical:0,high:0,medium:0,low:0};
            if (fs.existsSync(p)) {
              const r = JSON.parse(fs.readFileSync(p,'utf8'));
              s = r.results?.summary || r.summary || s;
            }
            const total = (s.critical||0)+(s.high||0)+(s.medium||0)+(s.low||0);
            const body =
            `## 🛡️ Vulnify Scan
            |Severity|Count|
            |--------|-----|
            |🔴 Critical|${s.critical||0}|
            |🟠 High|${s.high||0}|
            |🟡 Medium|${s.medium||0}|
            |🟢 Low|${s.low||0}|
            **Total:** ${total}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });

      - name: Fail on policy
        run: |
          crit=$(jq -r '.summary.critical // .results.summary.critical // 0' vulnify-report.json)
          high=$(jq -r '.summary.high // .results.summary.high // 0' vulnify-report.json)
          med=$(jq -r '.summary.medium // .results.summary.medium // 0' vulnify-report.json)
          low=$(jq -r '.summary.low // .results.summary.low // 0' vulnify-report.json)
          total=$((crit+high+med+low))
          if [ "${{ inputs.fail_on }}" = "high" ]; then
            [ $((crit+high)) -gt 0 ] && exit 1 || exit 0
          else
            [ "$total" -gt 0 ] && exit 1 || exit 0
          fi
